# Generated by Django 3.2.5 on 2021-07-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('seats', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('booked', models.BooleanField(default=False)),
                ('event_date', models.TextField(max_length=100)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.region')),
            ],
        ),
        migrations.AlterField(
            model_name='discount',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
