# Generated by Django 3.2.5 on 2021-07-23 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210721_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['booked']},
        ),
        migrations.AddField(
            model_name='event',
            name='age_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='main.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(through='main.Guest', to=settings.AUTH_USER_MODEL),
        ),
    ]
